package core.dao;

import java.util.List;
import core.bean.URolePermission;

public interface URolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insert(URolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    List<URolePermission> selectAll();
}