package core.dao;

import java.util.List;
import core.bean.URole;
import org.springframework.stereotype.Repository;

@Repository("URoleMapper")
public interface URoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int insert(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    URole selectByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    List<URole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(URole record);
    List<String> getroles();
}