package core.dao;

import java.util.List;
import core.bean.UUserRole;
import org.springframework.stereotype.Repository;

@Repository("UUserRoleMapper")
public interface UUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated
     */
    int insert(UUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated
     */
    List<UUserRole> selectAll();
    List<UUserRole> selectItemBypage();
}