package core.dao;

import java.util.List;
import core.bean.UUser;
import org.springframework.stereotype.Repository;

@Repository("UUserMapper")
public interface UUserMapper {

    int deleteByPrimaryKey(Long id);


    int insert(UUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbg.generated
     */
    UUser selectByPrimaryKey(Long id);


    List<UUser> selectAll();

    int updateByPrimaryKey(UUser record);

     List<UUser> selectUserBypage();
}