package core.bean;

import org.springframework.stereotype.Repository;

@Repository("URolePermission")
public class URolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.rid
     *
     * @mbg.generated
     */
    private int rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.pid
     *
     * @mbg.generated
     */
    private int pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.rid
     *
     * @return the value of u_role_permission.rid
     *
     * @mbg.generated
     */
    public int getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.rid
     *
     * @param rid the value for u_role_permission.rid
     *
     * @mbg.generated
     */
    public void setRid(int rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.pid
     *
     * @return the value of u_role_permission.pid
     *
     * @mbg.generated
     */
    public int getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.pid
     *
     * @param pid the value for u_role_permission.pid
     *
     * @mbg.generated
     */
    public void setPid(int pid) {
        this.pid = pid;
    }
}