package core.bean;

import org.springframework.stereotype.Repository;

@Repository("UUserRole")
public class UUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.uid
     *
     * @mbg.generated
     */
    private int uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.rid
     *
     * @mbg.generated
     */
    private int rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.uid
     *
     * @return the value of u_user_role.uid
     *
     * @mbg.generated
     */
    public int getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.uid
     *
     * @param uid the value for u_user_role.uid
     *
     * @mbg.generated
     */
    public void setUid(int uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.rid
     *
     * @return the value of u_user_role.rid
     *
     * @mbg.generated
     */
    public int getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.rid
     *
     * @param rid the value for u_user_role.rid
     *
     * @mbg.generated
     */
    public void setRid(int rid) {
        this.rid = rid;
    }
}